<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/mis_shared/bootstrap.php';
require_once __DIR__ . '/lib.php';
mis_require_login();
$user=mis_current_user();
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; form-action 'self'; base-uri 'none'; frame-ancestors 'self'");
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!mis_verify_csrf(isset($_POST['csrf_token'])?$_POST['csrf_token']:null)){throw new RuntimeException('頁面已逾時。');}
        $action=mis_post_string('action',30);$pdo=mis_db();$user=mis_current_user();
        if($action==='product'){
            if($user['role']!=='admin'){throw new RuntimeException('只有管理者可修改商品。');}
            $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT);$price=filter_input(INPUT_POST,'price',FILTER_VALIDATE_INT);$stock=filter_input(INPUT_POST,'stock',FILTER_VALIDATE_INT);
            if(!$id||$price===false||$price<0||$price>99999||$stock===false||$stock<0||$stock>9999){throw new InvalidArgumentException('價格或庫存不正確。');}
            $old=$pdo->prepare('SELECT stock FROM shop_products WHERE id=?');$old->execute(array($id));$oldStock=$old->fetchColumn();if($oldStock===false){throw new InvalidArgumentException('找不到商品。');}
            $pdo->beginTransaction();$pdo->prepare('UPDATE shop_products SET price=?,stock=?,active=?,updated_at=? WHERE id=?')->execute(array($price,$stock,isset($_POST['active'])?1:0,date('Y-m-d H:i:s'),$id));
            $delta=$stock-(int)$oldStock;if($delta!==0){$pdo->prepare('INSERT INTO shop_stock_movements (product_id,change_qty,reason,user_id,created_at) VALUES (?,?,\'manual\',?,?)')->execute(array($id,$delta,$user['id'],date('Y-m-d H:i:s')));} $pdo->commit();mis_audit('shop_product_updated','shop_product',(string)$id,array('price'=>$price,'stock'=>$stock));mis_flash('success','商品已更新。');
        }elseif($action==='order_status'){
            $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT);$status=mis_post_string('status',20);$allowed=array('received','preparing','ready','completed','cancelled');if(!$id||!in_array($status,$allowed,true)){throw new InvalidArgumentException('訂單狀態不正確。');}
            $pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM shop_orders WHERE id=?');$stmt->execute(array($id));$old=$stmt->fetchColumn();if($old===false){throw new InvalidArgumentException('找不到訂單。');}
            if($old==='cancelled'&&$status!=='cancelled'){throw new InvalidArgumentException('已取消訂單不可重新開啟。');}
            if($status==='cancelled'&&$old!=='cancelled'){$items=$pdo->prepare('SELECT product_id,quantity FROM shop_order_items WHERE order_id=? AND product_id IS NOT NULL');$items->execute(array($id));foreach($items->fetchAll() as $item){$pdo->prepare('UPDATE shop_products SET stock=stock+?,updated_at=? WHERE id=?')->execute(array($item['quantity'],date('Y-m-d H:i:s'),$item['product_id']));$pdo->prepare('INSERT INTO shop_stock_movements (product_id,order_id,change_qty,reason,user_id,created_at) VALUES (?,?,?,\'cancel_restore\',?,?)')->execute(array($item['product_id'],$id,$item['quantity'],$user['id'],date('Y-m-d H:i:s')));}}
            $pdo->prepare('UPDATE shop_orders SET status=?,updated_at=? WHERE id=?')->execute(array($status,date('Y-m-d H:i:s'),$id));$pdo->commit();mis_audit('shop_order_status','shop_order',(string)$id,array('from'=>$old,'to'=>$status));mis_flash('success','訂單狀態已更新。');
        }
    }catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction()){$pdo->rollBack();}mis_flash('error',($e instanceof InvalidArgumentException||$e instanceof RuntimeException)?$e->getMessage():'操作失敗。');}
    header('Location: '.mis_base_url('mis_shop/admin.php'));exit;
}
$products=shop_products(true);$orders=mis_db()->query('SELECT * FROM shop_orders ORDER BY id DESC LIMIT 100')->fetchAll();$counts=array('received'=>0,'preparing'=>0,'ready'=>0,'completed'=>0,'cancelled'=>0);foreach($orders as $o){$counts[$o['status']]++;}$tables=mis_db()->query('SELECT * FROM shop_tables WHERE active=1 ORDER BY id')->fetchAll();$labels=array('received'=>'已收到','preparing'=>'製作中','ready'=>'可取餐','completed'=>'已完成','cancelled'=>'已取消');
mis_render_header('商品點餐管理','shop');?><main class="app-main"><header class="page-head"><div><p class="eyebrow">SHOP ADMIN</p><h1>商品、訂單與 QR Code</h1><p>課程示範後台；商品價格及庫存變更會立即反映於公開目錄。</p></div><div class="admin-actions"><a class="secondary-button" href="<?=mis_e(mis_base_url('mis_shop/'))?>" target="_blank" rel="noopener">開啟點餐頁</a><a class="secondary-button" href="<?=mis_e(mis_base_url('mis_shop/analytics.php'))?>">分析與評估</a><?php if(mis_current_user()['role']==='admin'&&(mis_load_config()['environment']??'production')==='development'):?><a class="secondary-button" href="<?=mis_e(mis_base_url('mis_shop/generator.php'))?>">虛擬資料產生器</a><?php endif;?></div></header>
<section class="summary-grid"><?php foreach(array_slice($counts,0,4,true) as $key=>$value):?><div class="summary-card"><span><?=mis_e($labels[$key])?></span><strong><?=$value?></strong></div><?php endforeach;?></section>
<section class="panel"><h2>訂單看板</h2><?php if(!$orders):?><p class="muted">尚無訂單。</p><?php else:?><div class="table-wrap"><table><thead><tr><th>訂單／時間</th><th>桌號／姓名</th><th>金額</th><th>狀態</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?=mis_e($o['reference_no'])?><br><span class="muted"><?=mis_e($o['created_at'])?></span><?=$o['is_synthetic']?'<br><span class="badge">虛擬</span>':''?></td><td><?=mis_e($o['table_code'])?>／<?=mis_e($o['pickup_name'])?></td><td>NT$<?=(int)$o['total']?></td><td><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="order_status"><input type="hidden" name="id" value="<?=(int)$o['id']?>"><select name="status"<?=$o['status']==='cancelled'?' disabled':''?>><?php foreach($labels as $v=>$l):?><option value="<?=$v?>"<?=$o['status']===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select><button class="secondary-button"<?=$o['status']==='cancelled'?' disabled':''?>>更新</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>商品與成品庫存</h2><div class="table-wrap"><table><thead><tr><th>商品</th><th>價格</th><th>庫存</th><th>上架</th><th>操作</th></tr></thead><tbody><?php foreach($products as $p):$formId='product-'.(int)$p['id'];?><tr><td><?=mis_e($p['sku'])?><br><strong><?=mis_e($p['name'])?></strong></td><td><input form="<?=mis_e($formId)?>" type="number" name="price" min="0" max="99999" value="<?=(int)$p['price']?>"<?=$user['role']!=='admin'?' disabled':''?>></td><td><input form="<?=mis_e($formId)?>" type="number" name="stock" min="0" max="9999" value="<?=(int)$p['stock']?>"<?=$user['role']!=='admin'?' disabled':''?>></td><td><input form="<?=mis_e($formId)?>" type="checkbox" name="active" value="1"<?=$p['active']?' checked':''?><?=$user['role']!=='admin'?' disabled':''?>></td><td><form id="<?=mis_e($formId)?>" method="post"><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="product"><input type="hidden" name="id" value="<?=(int)$p['id']?>"><button class="secondary-button"<?=$user['role']!=='admin'?' disabled':''?>>儲存</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>桌號 QR Code</h2><p>可列印後放置桌面。若元件無法載入，下方仍顯示完整點餐網址供手動開啟。</p><div class="qr-grid"><?php foreach($tables as $table):$url=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').mis_base_url('mis_shop/?table='.rawurlencode($table['code']));?><article class="qr-card" data-qr="<?=mis_e($url)?>"><h3><?=mis_e($table['name'])?></h3><div class="qr-image" aria-label="<?=mis_e($table['name'])?> 點餐 QR Code"></div><p><a href="<?=mis_e($url)?>"><?=mis_e($url)?></a></p></article><?php endforeach;?></div></section></main><script src="assets/qrcode.min.js?v=2026083001"></script><script src="assets/admin-qr.js?v=2026083001" defer></script><?php mis_render_footer();?>
