<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/mis_shared/bootstrap.php';
require_once __DIR__ . '/lib.php';
mis_require_login();
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; form-action 'self'; base-uri 'none'; frame-ancestors 'self'");
$includeSynthetic = isset($_GET['synthetic']) && $_GET['synthetic'] === '1';
$pdo = mis_db();
$orderFilter = $includeSynthetic ? '' : ' AND o.is_synthetic=0';
$eventFilter = $includeSynthetic ? '' : ' WHERE e.is_synthetic=0';
$summary = array(
    'members'=>(int)$pdo->query('SELECT COUNT(*) FROM shop_customers'.($includeSynthetic?'':' WHERE is_synthetic=0'))->fetchColumn(),
    'orders'=>(int)$pdo->query("SELECT COUNT(*) FROM shop_orders o WHERE o.status!='cancelled'".$orderFilter)->fetchColumn(),
    'revenue'=>(int)$pdo->query("SELECT COALESCE(SUM(o.total),0) FROM shop_orders o WHERE o.status!='cancelled'".$orderFilter)->fetchColumn(),
    'events'=>(int)$pdo->query('SELECT COUNT(*) FROM shop_recommendation_events e'.$eventFilter)->fetchColumn(),
);
$products=$pdo->query("SELECT p.name,COALESCE(SUM(CASE WHEN o.status!='cancelled' THEN oi.quantity ELSE 0 END),0) quantity,COALESCE(SUM(CASE WHEN o.status!='cancelled' THEN oi.line_total ELSE 0 END),0) revenue FROM shop_products p LEFT JOIN shop_order_items oi ON oi.product_id=p.id LEFT JOIN shop_orders o ON o.id=oi.order_id".($includeSynthetic?'':' AND o.is_synthetic=0').' GROUP BY p.id ORDER BY quantity DESC,p.sort_order LIMIT 10')->fetchAll();
$methods=$pdo->query("SELECT e.method,SUM(CASE WHEN e.event_type='shown' THEN 1 ELSE 0 END) shown,SUM(CASE WHEN e.event_type='clicked' THEN 1 ELSE 0 END) clicked,SUM(CASE WHEN e.event_type='accepted' THEN 1 ELSE 0 END) accepted,SUM(CASE WHEN e.event_type='not_interested' THEN 1 ELSE 0 END) rejected,COUNT(DISTINCT e.product_id) diversity FROM shop_recommendation_events e".$eventFilter.' GROUP BY e.method ORDER BY e.method')->fetchAll();
$daily=$pdo->query("SELECT substr(o.created_at,1,10) day,COUNT(*) orders,SUM(o.total) revenue FROM shop_orders o WHERE o.status!='cancelled'".$orderFilter." AND o.created_at>=datetime('now','-13 days') GROUP BY substr(o.created_at,1,10) ORDER BY day")->fetchAll();
$recent=array_slice(array_map('intval',array_column($daily,'orders')),-7);$forecast=$recent?round(array_sum($recent)/count($recent),1):0;
$activeProducts=max(1,(int)$pdo->query('SELECT COUNT(*) FROM shop_products WHERE active=1')->fetchColumn());
$anomalies=$pdo->query("SELECT o.reference_no,o.pickup_name,o.total,o.created_at,SUM(oi.quantity) quantity FROM shop_orders o JOIN shop_order_items oi ON oi.order_id=o.id WHERE o.status!='cancelled'".$orderFilter.' GROUP BY o.id HAVING SUM(oi.quantity)>=6 OR o.total>=1000 ORDER BY o.created_at DESC LIMIT 30')->fetchAll();
$coldStart=(int)$pdo->query('SELECT COUNT(*) FROM shop_customers c WHERE '.($includeSynthetic?'1=1':'c.is_synthetic=0').' AND NOT EXISTS(SELECT 1 FROM shop_orders o WHERE o.customer_id=c.id)')->fetchColumn();
$maxQuantity=max(1,...array_map('intval',array_column($products,'quantity')));
mis_render_header('推薦分析與評估','shop',array('mis_shop/assets/analytics.css?v=2026083001'));
?><main class="app-main"><header class="page-head"><div><p class="eyebrow">ANALYTICS & EVALUATION</p><h1>推薦與營運教學分析</h1><p>比較推薦方法、商品銷售、需求趨勢與資料品質。預測是最近七個有資料日的簡單平均，不代表正式營運預測。</p></div><div class="admin-actions"><a class="secondary-button" href="<?=mis_e(mis_base_url('mis_shop/admin.php'))?>">返回商品後台</a><a class="secondary-button" href="<?=mis_e(mis_base_url('mis_shop/analytics.php?synthetic='.($includeSynthetic?'0':'1')))?>"><?=$includeSynthetic?'排除虛擬資料':'納入虛擬資料'?></a></div></header>
<section class="summary-grid"><div class="summary-card"><span>會員數</span><strong><?=$summary['members']?></strong></div><div class="summary-card"><span>有效訂單</span><strong><?=$summary['orders']?></strong></div><div class="summary-card"><span>示範營收</span><strong>NT$<?=number_format($summary['revenue'])?></strong></div><div class="summary-card"><span>推薦互動</span><strong><?=$summary['events']?></strong></div></section>
<section class="panel"><h2>推薦方法 A/B 指標</h2><p class="muted">點擊率＝clicked／shown；接受率＝accepted／shown；多樣性＝被推薦商品數／上架商品數。虛擬資料不得當作真實成效。</p><?php if(!$methods):?><p>尚無推薦互動，可先建立虛擬批次。</p><?php else:?><div class="table-wrap"><table><thead><tr><th>方法</th><th>曝光</th><th>點擊率</th><th>接受率</th><th>不感興趣</th><th>多樣性</th></tr></thead><tbody><?php foreach($methods as $row):$shown=max(1,(int)$row['shown']);?><tr><td><?=mis_e($row['method'])?></td><td><?=(int)$row['shown']?></td><td><?=number_format((int)$row['clicked']/$shown*100,1)?>%</td><td><?=number_format((int)$row['accepted']/$shown*100,1)?>%</td><td><?=(int)$row['rejected']?></td><td><?=number_format((int)$row['diversity']/$activeProducts*100,1)?>%</td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>熱門商品與銷售分布</h2><div class="analytics-bars"><?php foreach($products as $row):?><div class="analytics-bar"><span><?=mis_e($row['name'])?></span><div><i style="width:<?=number_format((int)$row['quantity']/$maxQuantity*100,1,'.','')?>%"></i></div><strong><?=(int)$row['quantity']?> 件／NT$<?=number_format((int)$row['revenue'])?></strong></div><?php endforeach;?></div></section>
<section class="panel"><h2>需求趨勢與簡單預測</h2><p>下一個教學日預估訂單：<strong><?=$forecast?></strong> 筆；冷啟動會員：<strong><?=$coldStart?></strong> 位。</p><?php if(!$daily):?><p class="muted">最近 14 天尚無資料。</p><?php else:?><div class="table-wrap"><table><thead><tr><th>日期</th><th>訂單</th><th>金額</th></tr></thead><tbody><?php foreach($daily as $row):?><tr><td><?=mis_e($row['day'])?></td><td><?=(int)$row['orders']?></td><td>NT$<?=number_format((int)$row['revenue'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>異常訂單候選</h2><p class="muted">單筆至少 6 件或 NT$1,000，只標記候選，不自動取消。</p><?php if(!$anomalies):?><p>目前沒有符合規則的訂單。</p><?php else:?><div class="table-wrap"><table><thead><tr><th>訂單</th><th>姓名</th><th>數量</th><th>金額</th><th>時間</th></tr></thead><tbody><?php foreach($anomalies as $row):?><tr><td><?=mis_e($row['reference_no'])?></td><td><?=mis_e($row['pickup_name'])?></td><td><?=(int)$row['quantity']?></td><td>NT$<?=number_format((int)$row['total'])?></td><td><?=mis_e($row['created_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main><?php mis_render_footer();?>
