<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/mis_shared/bootstrap.php';
require_once __DIR__ . '/lib.php';
$products = shop_products();
$customer = shop_customer();
$recommendations = shop_recommendations($customer, $products);
$tableCode = isset($_GET['table']) && is_string($_GET['table']) ? strtoupper(trim($_GET['table'])) : 'TAKEAWAY';
$table = shop_valid_table($tableCode);
if (!$table) { $tableCode = 'TAKEAWAY'; $table = shop_valid_table($tableCode); }
$categories = array();
foreach ($products as $p) { $categories[$p['category_code']] = $p['category_name']; }
?><!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>商品與 QR 點餐｜木窗咖啡</title><link rel="stylesheet" href="assets/shop.css?v=2026083001"><link rel="stylesheet" href="assets/shop-responsive.css?v=2026083001"></head>
<body data-order-url="submit-order.php">
<header class="shop-header"><a class="shop-brand" href="./"><span>WW</span><strong>木窗咖啡</strong></a><nav><a href="<?= mis_e(mis_base_url()) ?>">系統入口</a><?php if ($customer): ?><a href="member.php">嗨，<?= mis_e($customer['display_name']) ?></a><?php else: ?><a href="member.php">會員登入</a><?php endif; ?><button type="button" class="cart-button" data-cart-open>購物車 <span data-cart-count>0</span></button></nav></header>
<main class="shop-main">
  <section class="shop-hero"><div><p class="eyebrow">TEACHING MENU · <?= mis_e($table['name']) ?></p><h1>從今天的心情，找到一杯剛好的選擇。</h1><p>本頁商品與價格皆為課程示範資料，非正式營業菜單。可直接點餐，登入會員後可取得個人化推薦。</p></div><a class="primary-button" href="#menu">查看商品</a></section>
  <section class="recommend-section" aria-labelledby="recommend-title"><div class="section-head"><div><p class="eyebrow">FOR YOU</p><h2 id="recommend-title"><?= $customer ? '依你的偏好推薦' : '今日教學推薦' ?></h2></div><a href="ai-lab.php">開啟 AI 推薦實驗 →</a></div><div class="recommend-grid"><?php foreach ($recommendations as $p): ?><article><img src="assets/images/<?= mis_e($p['image_path']) ?>" alt="<?= mis_e($p['category_name']) ?>示範商品照片"><div><h3><?= mis_e($p['name']) ?></h3><p><?= mis_e($p['_reason']) ?></p><strong>NT$<?= (int) $p['price'] ?></strong></div></article><?php endforeach; ?></div></section>
  <section id="menu"><div class="section-head"><div><p class="eyebrow">MENU</p><h2>商品目錄</h2></div><label class="search-label">搜尋商品<input type="search" data-search maxlength="40" placeholder="例如：低甜、果香、拿鐵"></label></div><div class="filter-row"><button class="active" data-filter="all">全部</button><?php foreach ($categories as $code => $name): ?><button data-filter="<?= mis_e($code) ?>"><?= mis_e($name) ?></button><?php endforeach; ?></div>
  <div class="product-grid"><?php foreach ($products as $p): $search = implode(' ', array($p['name'],$p['description'],$p['flavors'],$p['texture'],$p['occasions'],$p['dietary'])); ?><article class="product-card" data-product data-category="<?= mis_e($p['category_code']) ?>" data-search="<?= mis_e($search) ?>"><img src="assets/images/<?= mis_e($p['image_path']) ?>" alt="<?= mis_e($p['category_name']) ?>示範商品照片" loading="lazy"><div class="product-body"><span class="product-category"><?= mis_e($p['category_name']) ?></span><h3><?= mis_e($p['name']) ?></h3><p><?= mis_e($p['description']) ?></p><div class="tag-row"><?php foreach (array_slice(array_merge(shop_tags($p['flavors']), shop_tags($p['texture']), shop_tags($p['occasions'])),0,3) as $tag): ?><span><?= mis_e($tag) ?></span><?php endforeach; ?></div><?php if ($p['allergens']): ?><p class="allergen">過敏原：<?= mis_e($p['allergens']) ?></p><?php endif; ?><div class="product-foot"><strong>NT$<?= (int) $p['price'] ?></strong><span>庫存 <?= (int) $p['stock'] ?></span></div><button type="button" class="primary-button" data-add data-id="<?= (int) $p['id'] ?>" data-name="<?= mis_e($p['name']) ?>" data-price="<?= (int) $p['price'] ?>" data-temperature="<?= mis_e($p['temperature']) ?>"<?= (int) $p['stock'] < 1 ? ' disabled' : '' ?>><?= (int) $p['stock'] < 1 ? '已售罄' : '加入購物車' ?></button></div></article><?php endforeach; ?></div></section>
</main>
<dialog class="cart-dialog" data-cart-dialog><form method="dialog" class="dialog-close"><button aria-label="關閉購物車">×</button></form><h2>你的購物車</h2><div data-cart-items><p class="muted">尚未加入商品。</p></div><form data-order-form><input type="hidden" name="csrf_token" value="<?= mis_e(mis_csrf_token()) ?>"><input type="hidden" name="table_code" value="<?= mis_e($tableCode) ?>"><input type="hidden" name="cart_json" data-cart-json><label>點餐方式<select name="service_type"><option value="dine_in"<?= $tableCode !== 'TAKEAWAY' ? ' selected' : '' ?>>內用</option><option value="takeaway"<?= $tableCode === 'TAKEAWAY' ? ' selected' : '' ?>>外帶</option></select></label><label>取餐姓名<input name="pickup_name" required maxlength="40" value="<?= mis_e($customer ? $customer['display_name'] : '') ?>"></label><p class="cart-total">總計 <strong data-cart-total>NT$0</strong></p><button class="primary-button" type="submit" data-submit-order>確認送出訂單</button><p data-order-status role="status"></p></form></dialog>
<footer class="shop-footer">木窗咖啡 WW Coffee · 課程示範系統</footer><script src="assets/shop.js?v=2026083001" defer></script></body></html>
