<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/mis_shared/bootstrap.php';
require_once __DIR__ . '/lib.php';
$error = ''; $message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if (!mis_verify_csrf(isset($_POST['csrf_token']) ? $_POST['csrf_token'] : null)) { throw new RuntimeException('頁面已逾時，請重新整理。'); }
        $action = mis_post_string('action', 20);
        if ($action === 'register') {
            $email = strtolower(mis_post_string('email', 254)); $name = mis_post_string('display_name', 40); $password = $email . '123';
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) { throw new InvalidArgumentException('請使用有效 Email。'); }
            $now=date('Y-m-d H:i:s'); $stmt=mis_db()->prepare('INSERT INTO shop_customers (email,password_hash,display_name,personalization_consent,created_at,updated_at) VALUES (?,?,?,?,?,?)');
            $stmt->execute(array($email,password_hash($password,PASSWORD_DEFAULT),$name,isset($_POST['consent'])?1:0,$now,$now));
            shop_customer_login($email,$password); $message='會員建立完成。';
        } elseif ($action === 'login') {
            if (!shop_customer_login(strtolower(mis_post_string('email',254)),mis_post_string('password',128))) { throw new InvalidArgumentException('Email 或密碼不正確。'); }
            $message='登入成功。';
        } elseif ($action === 'logout') { unset($_SESSION['shop_customer']); session_regenerate_id(true); header('Location: member.php'); exit;
        } elseif ($action === 'preference') {
            $customer=shop_customer(); if(!$customer){throw new RuntimeException('請先登入。');}
            $allowedCaffeine=array('any','none','low','medium','high'); $allowedTemperature=array('any','hot','cold');
            $caffeine=mis_post_string('caffeine',20); $temperature=mis_post_string('temperature',20); $budget=filter_input(INPUT_POST,'budget',FILTER_VALIDATE_INT);
            if(!in_array($caffeine,$allowedCaffeine,true)||!in_array($temperature,$allowedTemperature,true)||!$budget||$budget<50||$budget>2000){throw new InvalidArgumentException('偏好設定不正確。');}
            $values=array('categories','flavors','texture','avoid_allergens','occasions'); foreach($values as $key){$values[$key]=mis_post_string($key,200,false);}
            $stmt=mis_db()->prepare('INSERT INTO shop_preferences (customer_id,categories,caffeine,flavors,texture,temperature,sweetness,budget,avoid_allergens,occasions,updated_at) VALUES (:id,:categories,:caffeine,:flavors,:texture,:temperature,\'any\',:budget,:avoid,:occasions,:updated) ON CONFLICT(customer_id) DO UPDATE SET categories=excluded.categories,caffeine=excluded.caffeine,flavors=excluded.flavors,texture=excluded.texture,temperature=excluded.temperature,budget=excluded.budget,avoid_allergens=excluded.avoid_allergens,occasions=excluded.occasions,updated_at=excluded.updated_at');
            $stmt->execute(array(':id'=>$customer['id'],':categories'=>$values['categories'],':caffeine'=>$caffeine,':flavors'=>$values['flavors'],':texture'=>$values['texture'],':temperature'=>$temperature,':budget'=>$budget,':avoid'=>$values['avoid_allergens'],':occasions'=>$values['occasions'],':updated'=>date('Y-m-d H:i:s')));
            $consent=isset($_POST['consent'])?1:0; mis_db()->prepare('UPDATE shop_customers SET personalization_consent=:c,updated_at=:u WHERE id=:id')->execute(array(':c'=>$consent,':u'=>date('Y-m-d H:i:s'),':id'=>$customer['id'])); $_SESSION['shop_customer']['personalization_consent']=$consent; $message='偏好已更新。';
        } elseif ($action === 'favorite') {
            $customer=shop_customer(); $id=filter_input(INPUT_POST,'product_id',FILTER_VALIDATE_INT); if(!$customer||!$id){throw new InvalidArgumentException('收藏資料不正確。');}
            $stmt=mis_db()->prepare('INSERT OR IGNORE INTO shop_favorites (customer_id,product_id,created_at) VALUES (?,?,?)');$stmt->execute(array($customer['id'],$id,date('Y-m-d H:i:s')));$message='已加入收藏。';
        } elseif ($action === 'clear_recommendations') {
            $customer=shop_customer();if(!$customer){throw new RuntimeException('請先登入。');}mis_db()->prepare('DELETE FROM shop_recommendation_events WHERE customer_id=:id')->execute(array(':id'=>$customer['id']));$message='推薦互動紀錄已清除。';
        }
    } catch (PDOException $e) { $error=strpos($e->getMessage(),'UNIQUE')!==false?'此 Email 已註冊。':'目前無法儲存資料。'; }
    catch (Throwable $e) { $error=($e instanceof InvalidArgumentException||$e instanceof RuntimeException)?$e->getMessage():'操作失敗。'; }
}
$customer=shop_customer();$preference=null;$orders=array();$favorites=array();
if($customer){$stmt=mis_db()->prepare('SELECT * FROM shop_preferences WHERE customer_id=?');$stmt->execute(array($customer['id']));$preference=$stmt->fetch();$stmt=mis_db()->prepare('SELECT reference_no,total,status,created_at FROM shop_orders WHERE customer_id=? ORDER BY id DESC LIMIT 20');$stmt->execute(array($customer['id']));$orders=$stmt->fetchAll();$stmt=mis_db()->prepare('SELECT p.* FROM shop_favorites f JOIN shop_products p ON p.id=f.product_id WHERE f.customer_id=?');$stmt->execute(array($customer['id']));$favorites=$stmt->fetchAll();}
?><!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>會員中心｜木窗咖啡</title><link rel="stylesheet" href="assets/shop.css?v=2026083001"></head><body><header class="shop-header"><a class="shop-brand" href="./"><span>WW</span><strong>會員中心</strong></a><nav><a href="./">返回商品</a></nav></header><main>
<?php if($message):?><div class="panel notice" role="status"><?=mis_e($message)?></div><?php endif;?><?php if($error):?><div class="panel notice error" role="alert"><?=mis_e($error)?></div><?php endif;?>
<?php if(!$customer):?><section class="panel"><h1>會員登入或註冊</h1><p>免登入也可以點餐；會員可保存偏好、收藏及歷史訂單。此 development 教學站的會員密碼固定為完整 Email 帳號加 123。</p><div class="form-grid"><form method="post"><h2>登入</h2><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="login"><label>Email<input type="email" name="email" maxlength="254" required></label><label>密碼<input type="password" name="password" maxlength="128" required></label><button class="primary-button">登入</button></form><form method="post"><h2>建立會員</h2><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="register"><label>顯示名稱<input name="display_name" maxlength="40" required></label><label>Email<input type="email" name="email" maxlength="254" required></label><p class="muted">密碼將設定為「完整 Email＋123」。</p><label><input type="checkbox" name="consent" value="1">同意使用偏好與訂單提供個人化推薦</label><button class="primary-button">註冊</button></form></div></section>
<?php else:?><section class="panel"><div class="panel-head"><div><p class="eyebrow">MEMBER</p><h1><?=mis_e($customer['display_name'])?></h1><p><?=mis_e($customer['email'])?></p></div><form method="post"><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="logout"><button class="secondary-button">登出</button></form></div></section>
<section class="panel"><h2>推薦偏好</h2><p>以逗號分隔多個項目，例如「果香,花香」。過敏原會直接排除，不只影響分數。</p><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="preference"><label>常選分類<input name="categories" maxlength="200" value="<?=mis_e($preference?$preference['categories']:'咖啡,點心')?>"></label><label>風味<input name="flavors" maxlength="200" value="<?=mis_e($preference?$preference['flavors']:'果香,堅果')?>"></label><label>口感<input name="texture" maxlength="200" value="<?=mis_e($preference?$preference['texture']:'清爽')?>"></label><label>情境<input name="occasions" maxlength="200" value="<?=mis_e($preference?$preference['occasions']:'下午茶')?>"></label><label>咖啡因<select name="caffeine"><?php foreach(array('any'=>'不限','none'=>'無','low'=>'低','medium'=>'中','high'=>'高') as $v=>$l):?><option value="<?=$v?>"<?=($preference?$preference['caffeine']:'any')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>溫度<select name="temperature"><?php foreach(array('any'=>'不限','hot'=>'熱','cold'=>'冰') as $v=>$l):?><option value="<?=$v?>"<?=($preference?$preference['temperature']:'any')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>單品預算<input type="number" name="budget" min="50" max="2000" value="<?=(int)($preference?$preference['budget']:200)?>"></label><label>避開過敏原<input name="avoid_allergens" maxlength="200" value="<?=mis_e($preference?$preference['avoid_allergens']:'')?>" placeholder="奶類,堅果"></label><label class="full"><input type="checkbox" name="consent" value="1"<?=$customer['personalization_consent']?' checked':''?>>同意使用偏好、收藏與完成訂單提供個人化推薦</label><button class="primary-button">儲存偏好</button></form></section>
<section class="panel"><h2>收藏</h2><?php if(!$favorites):?><p class="muted">尚無收藏，可在下方加入。</p><?php else:?><p><?=mis_e(implode('、',array_column($favorites,'name')))?></p><?php endif;?><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="favorite"><label>加入商品<select name="product_id"><?php foreach(shop_products() as $p):?><option value="<?=(int)$p['id']?>"><?=mis_e($p['name'])?></option><?php endforeach;?></select></label><button class="secondary-button">加入收藏</button></form></section>
<section class="panel"><h2>歷史訂單</h2><?php if(!$orders):?><p class="muted">尚無訂單。</p><?php else:?><div class="table-wrap"><table><thead><tr><th>訂單</th><th>總額</th><th>狀態</th><th>時間</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?=mis_e($o['reference_no'])?></td><td>NT$<?=(int)$o['total']?></td><td><?=mis_e($o['status'])?></td><td><?=mis_e($o['created_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=mis_e(mis_csrf_token())?>"><input type="hidden" name="action" value="clear_recommendations"><button class="secondary-button" data-confirm="只清除推薦互動紀錄，確定繼續？">清除推薦紀錄</button></form></section><?php endif;?></main><footer class="shop-footer">會員資料僅供課程示範，請勿輸入真實敏感資料。</footer><script src="../mis_shared/assets/internal.js?v=2026083001" defer></script></body></html>
