const CDN='https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1?v=2026083001';
export function createTextLab(config){
 const q=(s)=>document.querySelector(s),load=q('#load-button'),run=q('#run-button'),status=q('#status-text'),progress=q('#progress'),percent=q('#progress-text'),detail=q('#status-detail'),action=q('#action-status'),human=q('#human-output'),raw=q('#raw-output');let pipe=null,mod=null;
 const message=(text,type='')=>{action.textContent=text;action.className=`action-status${type?` ${type}`:''}`};
 const update=(d)=>{if(!d)return;if(d.status==='progress'&&Number.isFinite(d.progress)){progress.value=d.progress;percent.textContent=`${d.progress.toFixed(0)}%`;status.textContent='模型下載中'}else if(d.status==='initiate')status.textContent='準備模型檔案';else if(d.status==='done')status.textContent='載入模型中';if(d.file)detail.textContent=`目前檔案：${String(d.file).split('/').pop()}`};
 load.addEventListener('click',async()=>{load.disabled=true;run.disabled=true;status.textContent='準備 Transformers.js';detail.textContent='正在連線至 CDN 與 Hugging Face Hub…';message('模型載入中…');try{if(!mod)mod=await import(CDN);pipe=await mod.pipeline(config.task,config.model,{dtype:config.dtype||'q8',progress_callback:update});progress.value=100;percent.textContent='100%';status.textContent='模型載入完成';detail.textContent='模型已就緒；再次載入通常會使用 Browser Cache。';run.disabled=false;message('可以開始實驗。','success')}catch(e){console.error('Model loading failed:',e);pipe=null;status.textContent='模型載入失敗';detail.textContent=e instanceof Error?e.message:'未知錯誤';message('請檢查網路、記憶體或模型相容性。','error')}finally{load.disabled=false}});
 run.addEventListener('click',async()=>{if(!pipe){message('請先載入模型。','error');return}let input;try{input=config.read();if(!input)throw new Error('請完整填寫輸入內容。')}catch(e){message(e.message,'error');return}run.disabled=true;load.disabled=true;message('AI 執行中…');try{const output=await config.infer(pipe,input);config.render(output,human);raw.textContent=JSON.stringify(output,null,2);message('執行完成。','success')}catch(e){console.error('Inference failed:',e);message('執行失敗。請縮短輸入或重新載入模型。','error')}finally{run.disabled=false;load.disabled=false}});
 document.querySelectorAll('[data-sample]').forEach(b=>b.addEventListener('click',()=>config.sample(JSON.parse(b.dataset.sample))));
}
export function textResult(text,node){node.textContent=text}
export function listResult(items,node){node.replaceChildren(...items.map(x=>{const d=document.createElement('div');d.className='output-item';d.textContent=x;return d}))}
